version: '3'

services:
  sportseventspredictions:
    build: ./apache_airflow
    volumes:
      - ./apache_airflow/dags:/opt/airflow/dags
      - ./apache_airflow/scripts:/opt/airflow/scripts
      - ./data:/opt/airflow/data
      - ./apache_airflow/airflow/airflow.cfg:/opt/airflow/airflow.cfg
    environment:
      - PYTHONPATH=/opt/airflow

    ports:
      - "8080:8080"

    command: airflow standalone

  postgres:
    build: ./postgresql
    
    ports:
      - "5432:5432"

    volumes:
      - ./postgres-data:/var/lib/postgresql/data