version: '3'

services:
  sportseventspredictions:
    build: ./apache_airflow

    volumes:
      - ./airflow:/opt/airflow

    ports:
      - "8080:8080"

    command: airflow standalone
  postgres:
    build: ./postgresql
    
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data