version: '3'

services:
  apache_airflow:
    build:
      context: ./apache_airflow
      dockerfile: Dockerfile  
    depends_on:
      - postgresql
    restart: always
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 2g
    volumes:
      - ./apache_airflow/models:/opt/airflow/models
      - ./apache_airflow/dags:/opt/airflow/dags
      - ./apache_airflow/scripts:/opt/airflow/scripts
      - ./data:/opt/airflow/data
    environment:
      - AIRFLOW__WEBSERVER__RATE_LIMIT_STORAGE_URL=postgresql+psycopg2://postgres:pass@postgresql/preds
      - PYTHONPATH=/opt/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__WEBSERVER__WEB_SERVER_MASTER_TIMEOUT=300
      - AIRFLOW__WEBSERVER__WEB_SERVER_WORKER_TIMEOUT=300
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://postgres:pass@postgresql/preds
      - AIRFLOW_CONN_POSTGRES_DEFAULT=postgresql+psycopg2://postgres:pass@postgresql/preds
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      
    ports:
      - "8080:8080"

    command: >
      bash -c "
      airflow db init &&
      airflow users create --username admin --password admin --firstname admin --lastname admin --role Admin --email admin@example.com &&
      airflow standalone"

  postgresql:
    build: ./postgresql

    environment:
      POSTGRES_DB: preds
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass

    ports:
      - "5432:5432"

    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
      timeout: 5s

  pgbackup:
    image: postgres:latest
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./backups:/backups
    entrypoint: /bin/sh -c "while true; do pg_dump -U postgresql -h postgres preds > /backups/backup_\$(date +\%F_\%T).sql; sleep 86400; done"

volumes:
  postgresql: