version: '3'

services:
  sportseventspredictions:
    build: ./apache_airflow
    depends_on:
      - postgres
    restart: always
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4g
    volumes:
      - ./apache_airflow/dags:/opt/airflow/dags
      - ./apache_airflow/scripts:/opt/airflow/scripts
      - ./data:/opt/airflow/data
      - ./apache_airflow/airflow/airflow.cfg:/opt/airflow/airflow.cfg
    environment:
      - PYTHONPATH=/opt/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__WEBSERVER__WEB_SERVER_MASTER_TIMEOUT=300
      - AIRFLOW__WEBSERVER__WEB_SERVER_WORKER_TIMEOUT=300
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://postgres:pass@postgres/preds

    ports:
      - "8080:8080"

    command: >
      bash -c "
      airflow db init &&
      airflow users create --username admin --password admin --firstname admin --lastname admin --role Admin --email admin@example.com &&
      airflow standalone"

  postgres:
    build: ./postgresql

    environment:
      POSTGRES_DB: preds
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass

    ports:
      - "5432:5432"

    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  pgbackups:
    image: postgres:latest
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./backups:/backups
    entrypoint: /bin/sh -c "while true; do pg_dump -U postgres -h postgres preds > /backups/backup_\$(date +\%F_\%T).sql; sleep 86400; done"

volumes:
  postgres_data: